-- V5__new_tables.sql

CREATE TABLE ONU_DIST (
  ID int(11) NOT NULL AUTO_INCREMENT,
  CUSTOMERS_ID int(11) NOT NULL,
  DIST int(11) NOT NULL,
  PRIMARY KEY (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE SERVICES_PON_PORTS (
  id int(11) NOT NULL AUTO_INCREMENT,
  PON_ID int(11) NOT NULL,
  SERVICE_ID int(11) NOT NULL,
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;