services:
  raisepondb:
    build:
      context: ./db/
    image: vtvelkov/raisepon_db
    container_name: raisepon_db
    command: --lower_case_table_names=1
    volumes:
      - raisedb:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=WPvbdUbIk5
      - MYSQL_DATABASE=raisepon
      - MYSQL_USER=raisepon
      - MYSQL_PASSWORD=r41sepon
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -uroot -p$$MYSQL_ROOT_PASSWORD --silent"]
      interval: 5s
      timeout: 5s
      retries: 30
      start_period: 20s
    restart: unless-stopped
    networks:
      - raisepon_net
  flyway:
    build:
      context: ./flyway/
    image: vtvelkov/raisepon_flyway
    container_name: raisepon_flyway
    depends_on:
      raisepondb:
        condition: service_healthy
    entrypoint: ["flyway"]
    command:
      - "-url=jdbc:mysql://raisepondb:3306/raisepon?allowPublicKeyRetrieval=true&useSSL=false"
      - "-user=root"
      - "-password=WPvbdUbIk5"
      - "-baselineOnMigrate=true"
      - "-validateOnMigrate=true"
      - "migrate"
    volumes: []
    restart: on-failure
    networks:
      - raisepon_net
    environment:
      - FLYWAY_LOCATIONS=filesystem:/flyway/sql
  raiseponweb:
    build:
      context: ./web/
    image: vtvelkov/raisepon_web
    container_name: raisepon_web
    ports:
      - "8088:80"
    volumes:
      - raisewebrrd:/var/www/html/rrd
      - raiselog:/var/log/raisepon
    restart: unless-stopped
    networks:
        - raisepon_net
  rsyslog:
    build:
      context: ./rsyslog/
    image: vtvelkov/rsyslog
    container_name: raisepon_rsyslog
    ports:
      - "1514:514/udp"
    volumes:
      - raiselog:/var/log/raisepon
    restart: unless-stopped
    networks:
      - raisepon_net
volumes:
  raisedb: {}
  raisewebrrd: {}
  raiselog: {}
networks:
  raisepon_net:
    driver: bridge